version: '3.5'

volumes:
  postgres-data:
  elasticsearch-data:
  s3-data:
  redis-data:

services:
  postgres:
    image: "postgres:10.15@sha256:95f79893ef4d769277f7687b03bb24fe77a49ad2ec1c269f89a0cf849d6f4c7b"                                                                   
    ports:
      - "5432:5432"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: $USER
      POSTGRES_HOST_AUTH_METHOD: trust

  elasticsearch:
    image: "elasticsearch:7.9.3"
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    environment:
      - "discovery.type=single-node"

  nginx:
    image: "nginx:1.14-alpine"
    ports:
      - "80:80"
    volumes:
      - "./dmrunner-nginx/nginx.conf:/etc/nginx/nginx.conf:ro"

  s3:
    image: "localstack/localstack@sha256:cb08eabae40fa1e33babffa4ff8c454c2276405cfc2fe1e2e300e5625244bdf7"
    ports:
      - "4566:4566"
      - "4571:4571"
    environment:
      - SERVICES=s3
      - DATA_DIR=/tmp/localstack
      - DEFAULT_REGION=eu-west-1
    volumes:
      - "s3-data:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
  
  redis:
    image: "redis:5"
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
